name: SkyblockCore
version: 1.1.0
main: com.sujal.skyblockcore.SkyblockCore
api-version: '1.21'
author: Sujal
depend: [HypixelConnect]
commands:
  sb:
    description: Main Skyblock command
  hub:
    description: Teleport to hub
  warp:
    description: Teleport to zones
    
