name: Build SkyblockCore

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout SkyblockCore Repo
      uses: actions/checkout@v3

    # Yeh step aapki pehli repository (HypixelConnect) ko download karega
    - name: Checkout HypixelConnect API Repo
      uses: actions/checkout@v3
      with:
        repository: 'sujalofficial07/HypixelConnect' # <--- YAHAN APNA USERNAME DAALEIN
        path: 'HypixelConnect-Source'

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Pehle HypixelConnect ko install karega
    - name: Install HypixelConnect API
      run: mvn clean install -f HypixelConnect-Source/pom.xml

    # Phir SkyblockCore ko build karega
    - name: Build SkyblockCore
      run: mvn clean package

    - name: Upload Core Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SkyblockCore-JAR
        path: target/HypixelCore-*.jar
        
